// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	UserID        int64     `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"`          // 用户ID
	DeptID        int64     `gorm:"column:dept_id;comment:部门ID" json:"dept_id"`                     // 部门ID
	LoginName     string    `gorm:"column:login_name;not null;comment:登录账号" json:"login_name"`      // 登录账号
	UserName      string    `gorm:"column:user_name;comment:用户昵称" json:"user_name"`                 // 用户昵称
	UserType      string    `gorm:"column:user_type;comment:用户类型（00系统用户 01注册用户）" json:"user_type"`  // 用户类型（00系统用户 01注册用户）
	Email         string    `gorm:"column:email;comment:用户邮箱" json:"email"`                         // 用户邮箱
	Phonenumber   string    `gorm:"column:phonenumber;comment:手机号码" json:"phonenumber"`             // 手机号码
	Sex           string    `gorm:"column:sex;comment:用户性别（0男 1女 2未知）" json:"sex"`                  // 用户性别（0男 1女 2未知）
	Avatar        string    `gorm:"column:avatar;comment:头像路径" json:"avatar"`                       // 头像路径
	Password      string    `gorm:"column:password;comment:密码" json:"password"`                     // 密码
	Salt          string    `gorm:"column:salt;comment:盐加密" json:"salt"`                            // 盐加密
	Status        string    `gorm:"column:status;comment:帐号状态（0正常 1停用）" json:"status"`              // 帐号状态（0正常 1停用）
	DelFlag       string    `gorm:"column:del_flag;comment:删除标志（0代表存在 2代表删除）" json:"del_flag"`      // 删除标志（0代表存在 2代表删除）
	LoginIP       string    `gorm:"column:login_ip;comment:最后登录IP" json:"login_ip"`                 // 最后登录IP
	LoginDate     time.Time `gorm:"column:login_date;comment:最后登录时间" json:"login_date"`             // 最后登录时间
	PwdUpdateDate time.Time `gorm:"column:pwd_update_date;comment:密码最后更新时间" json:"pwd_update_date"` // 密码最后更新时间
	CreateBy      string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                  // 创建者
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`             // 创建时间
	UpdateBy      string    `gorm:"column:update_by;comment:更新者" json:"update_by"`                  // 更新者
	UpdateTime    time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`             // 更新时间
	Remark        string    `gorm:"column:remark;comment:备注" json:"remark"`                         // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
