// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysLogininfor = "sys_logininfor"

// SysLogininfor mapped from table <sys_logininfor>
type SysLogininfor struct {
	InfoID        int64     `gorm:"column:info_id;primaryKey;comment:访问ID" json:"info_id"`    // 访问ID
	UserName      string    `gorm:"column:user_name;comment:用户账号" json:"user_name"`           // 用户账号
	Ipaddr        string    `gorm:"column:ipaddr;comment:登录IP地址" json:"ipaddr"`               // 登录IP地址
	LoginLocation string    `gorm:"column:login_location;comment:登录地点" json:"login_location"` // 登录地点
	Browser       string    `gorm:"column:browser;comment:浏览器类型" json:"browser"`              // 浏览器类型
	Os            string    `gorm:"column:os;comment:操作系统" json:"os"`                         // 操作系统
	Status        string    `gorm:"column:status;comment:登录状态（0成功 1失败）" json:"status"`        // 登录状态（0成功 1失败）
	Msg           string    `gorm:"column:msg;comment:提示消息" json:"msg"`                       // 提示消息
	LoginTime     time.Time `gorm:"column:login_time;comment:访问时间" json:"login_time"`         // 访问时间
}

// TableName SysLogininfor's table name
func (*SysLogininfor) TableName() string {
	return TableNameSysLogininfor
}
