// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGenTableColumn = "gen_table_column"

// GenTableColumn mapped from table <gen_table_column>
type GenTableColumn struct {
	ColumnID      int64     `gorm:"column:column_id;primaryKey;comment:编号" json:"column_id"`                  // 编号
	TableID       int64     `gorm:"column:table_id;comment:归属表编号" json:"table_id"`                            // 归属表编号
	ColumnName    string    `gorm:"column:column_name;comment:列名称" json:"column_name"`                        // 列名称
	ColumnComment string    `gorm:"column:column_comment;comment:列描述" json:"column_comment"`                  // 列描述
	ColumnType    string    `gorm:"column:column_type;comment:列类型" json:"column_type"`                        // 列类型
	JavaType      string    `gorm:"column:java_type;comment:JAVA类型" json:"java_type"`                         // JAVA类型
	JavaField     string    `gorm:"column:java_field;comment:JAVA字段名" json:"java_field"`                      // JAVA字段名
	IsPk          string    `gorm:"column:is_pk;comment:是否主键（1是）" json:"is_pk"`                               // 是否主键（1是）
	IsIncrement   string    `gorm:"column:is_increment;comment:是否自增（1是）" json:"is_increment"`                 // 是否自增（1是）
	IsRequired    string    `gorm:"column:is_required;comment:是否必填（1是）" json:"is_required"`                   // 是否必填（1是）
	IsInsert      string    `gorm:"column:is_insert;comment:是否为插入字段（1是）" json:"is_insert"`                    // 是否为插入字段（1是）
	IsEdit        string    `gorm:"column:is_edit;comment:是否编辑字段（1是）" json:"is_edit"`                         // 是否编辑字段（1是）
	IsList        string    `gorm:"column:is_list;comment:是否列表字段（1是）" json:"is_list"`                         // 是否列表字段（1是）
	IsQuery       string    `gorm:"column:is_query;comment:是否查询字段（1是）" json:"is_query"`                       // 是否查询字段（1是）
	QueryType     string    `gorm:"column:query_type;comment:查询方式（等于、不等于、大于、小于、范围）" json:"query_type"`        // 查询方式（等于、不等于、大于、小于、范围）
	HTMLType      string    `gorm:"column:html_type;comment:显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）" json:"html_type"` // 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	DictType      string    `gorm:"column:dict_type;comment:字典类型" json:"dict_type"`                           // 字典类型
	Sort          int32     `gorm:"column:sort;comment:排序" json:"sort"`                                       // 排序
	CreateBy      string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                            // 创建者
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                       // 创建时间
	UpdateBy      string    `gorm:"column:update_by;comment:更新者" json:"update_by"`                            // 更新者
	UpdateTime    time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                       // 更新时间
}

// TableName GenTableColumn's table name
func (*GenTableColumn) TableName() string {
	return TableNameGenTableColumn
}
