// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	MenuID     int64     `gorm:"column:menu_id;primaryKey;comment:菜单ID" json:"menu_id"`             // 菜单ID
	MenuName   string    `gorm:"column:menu_name;not null;comment:菜单名称" json:"menu_name"`           // 菜单名称
	ParentID   int64     `gorm:"column:parent_id;comment:父菜单ID" json:"parent_id"`                   // 父菜单ID
	OrderNum   int32     `gorm:"column:order_num;comment:显示顺序" json:"order_num"`                    // 显示顺序
	URL        string    `gorm:"column:url;comment:请求地址" json:"url"`                                // 请求地址
	Target     string    `gorm:"column:target;comment:打开方式（menuItem页签 menuBlank新窗口）" json:"target"` // 打开方式（menuItem页签 menuBlank新窗口）
	MenuType   string    `gorm:"column:menu_type;comment:菜单类型（M目录 C菜单 F按钮）" json:"menu_type"`       // 菜单类型（M目录 C菜单 F按钮）
	Visible    string    `gorm:"column:visible;comment:菜单状态（0显示 1隐藏）" json:"visible"`               // 菜单状态（0显示 1隐藏）
	IsRefresh  string    `gorm:"column:is_refresh;comment:是否刷新（0刷新 1不刷新）" json:"is_refresh"`        // 是否刷新（0刷新 1不刷新）
	Perms      string    `gorm:"column:perms;comment:权限标识" json:"perms"`                            // 权限标识
	Icon       string    `gorm:"column:icon;comment:菜单图标" json:"icon"`                              // 菜单图标
	CreateBy   string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                     // 创建者
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                // 创建时间
	UpdateBy   string    `gorm:"column:update_by;comment:更新者" json:"update_by"`                     // 更新者
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                // 更新时间
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`                            // 备注
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
