# config.yaml 示例
debug: true # 设置是否开启调试模式
language: "zh-CN" # 应用默认语言

server:
  port: 8080 # 服务器监听端口

database:
  dbtype: "postgres"
  host: "172.16.10.215" # 数据库地址
  port: 5432 # 数据库端口
  user: "postgres" # 数据库用户名
  password: "postgresql.123456" # 数据库密码
  dbname: "" # 数据库名称

# 根据需要添加更多配置项