# Copyright (c) [2024] K. All rights reserved.
# Use of this source code is governed by a MIT license that can be found in the LICENSE file.
# Author: K.
# Email: hot_kun@hotmail.com or BusinessCallKun@gmail.com
# File: config.yaml

debug: true # 设置是否开启调试模式
language: "zh-CN" # 应用默认语言

server:
  port: 8080 # 服务器监听端口

database:
  dbtype: "postgresql"
  host: "172.16.10.215" # 数据库地址
  port: 5432 # 数据库端口
  user: "postgres" # 数据库用户名
  password: "postgresql.123456" # 数据库密码
  dbname: "" # 数据库名称

# 根据需要添加更多配置项
redis:
  host: "111.230.61.77"
  port: 6379
  password: ""
  db: 0
  max_idle_conns: 10