// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum mapped from table <sys_dict_data>
type SysDictDatum struct {
	DictCode   int64     `gorm:"column:dict_code;primaryKey;comment:字典编码" json:"dict_code"` // 字典编码
	DictSort   int32     `gorm:"column:dict_sort;comment:字典排序" json:"dict_sort"`            // 字典排序
	DictLabel  string    `gorm:"column:dict_label;comment:字典标签" json:"dict_label"`          // 字典标签
	DictValue  string    `gorm:"column:dict_value;comment:字典键值" json:"dict_value"`          // 字典键值
	DictType   string    `gorm:"column:dict_type;comment:字典类型" json:"dict_type"`            // 字典类型
	CSSClass   string    `gorm:"column:css_class;comment:样式属性（其他样式扩展）" json:"css_class"`    // 样式属性（其他样式扩展）
	ListClass  string    `gorm:"column:list_class;comment:表格回显样式" json:"list_class"`        // 表格回显样式
	IsDefault  string    `gorm:"column:is_default;comment:是否默认（Y是 N否）" json:"is_default"`   // 是否默认（Y是 N否）
	Status     string    `gorm:"column:status;comment:状态（0正常 1停用）" json:"status"`           // 状态（0正常 1停用）
	CreateBy   string    `gorm:"column:create_by;comment:创建者" json:"create_by"`             // 创建者
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`        // 创建时间
	UpdateBy   string    `gorm:"column:update_by;comment:更新者" json:"update_by"`             // 更新者
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`        // 更新时间
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`                    // 备注
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
