// Copyright (c) [2024] K. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file. or see：https://github.com/Kun-GitHub/RuoYi-Go/blob/main/LICENSE
// Author: K. See：https://github.com/Kun-GitHub/RuoYi-Go or https://gitee.com/gitee_kun/RuoYi-Go
// Email: hot_kun@hotmail.com or 867917691@qq.com

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "sys_user_role"

// SysUserRole mapped from table <sys_user_role>
type SysUserRole struct {
	UserID int64 `gorm:"column:user_id;primaryKey;comment:用户ID" json:"userId"` // 用户ID
	RoleID int64 `gorm:"column:role_id;primaryKey;comment:角色ID" json:"roleId"` // 角色ID
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
