// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserPost = "sys_user_post"

// SysUserPost mapped from table <sys_user_post>
type SysUserPost struct {
	UserID int64 `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"` // 用户ID
	PostID int64 `gorm:"column:post_id;primaryKey;comment:岗位ID" json:"post_id"` // 岗位ID
}

// TableName SysUserPost's table name
func (*SysUserPost) TableName() string {
	return TableNameSysUserPost
}
