// Copyright (c) [2024] K. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file. or see：https://github.com/Kun-GitHub/RuoYi-Go/blob/main/LICENSE
// Author: K. See：https://github.com/Kun-GitHub/RuoYi-Go or https://gitee.com/gitee_kun/RuoYi-Go
// Email: hot_kun@hotmail.com or 867917691@qq.com

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysConfig = "sys_config"

// SysConfig mapped from table <sys_config>
type SysConfig struct {
	ConfigID    int64     `gorm:"column:config_id;primaryKey;comment:参数主键" json:"configId"`                // 参数主键
	ConfigName  string    `gorm:"column:config_name;comment:参数名称" json:"configName" validate:"required"`   // 参数名称
	ConfigKey   string    `gorm:"column:config_key;comment:参数键名" json:"configKey" validate:"required"`     // 参数键名
	ConfigValue string    `gorm:"column:config_value;comment:参数键值" json:"configValue" validate:"required"` // 参数键值
	ConfigType  string    `gorm:"column:config_type;comment:系统内置（Y是 N否）" json:"configType"`                // 系统内置（Y是 N否）
	CreateBy    string    `gorm:"column:create_by;comment:创建者" json:"createBy"`                            // 创建者
	CreateTime  time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`                       // 创建时间
	UpdateBy    string    `gorm:"column:update_by;comment:更新者" json:"updateBy"`                            // 更新者
	UpdateTime  time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`                       // 更新时间
	Remark      string    `gorm:"column:remark;comment:备注" json:"remark"`                                  // 备注
}

// TableName SysConfig's table name
func (*SysConfig) TableName() string {
	return TableNameSysConfig
}

// SysConfigRequest mapped from table <SysConfigRequest>
type SysConfigRequest struct {
	ConfigType string `json:"configType"`
	ConfigName string `json:"configName"`
	ConfigKey  string `json:"configKey"`
	BeginTime  string `json:"beginTime"`
	EndTime    string `json:"endTime"`
}
