// Copyright (c) [2024] K. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file. or see：https://github.com/Kun-GitHub/RuoYi-Go/blob/main/LICENSE
// Author: K. See：https://github.com/Kun-GitHub/RuoYi-Go
// Email: hot_kun@hotmail.com or 867917691@qq.com

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	MenuID     int64     `gorm:"column:menu_id;primaryKey;comment:菜单ID" json:"menuId"`       // 菜单ID
	MenuName   string    `gorm:"column:menu_name;not null;comment:菜单名称" json:"menuName"`     // 菜单名称
	ParentID   int64     `gorm:"column:parent_id;comment:父菜单ID" json:"parentId"`             // 父菜单ID
	OrderNum   int32     `gorm:"column:order_num;comment:显示顺序" json:"orderNum"`              // 显示顺序
	Path       string    `gorm:"column:path;comment:路由地址" json:"path"`                       // 路由地址
	Component  string    `gorm:"column:component;comment:组件路径" json:"component"`             // 组件路径
	Query      string    `gorm:"column:query;comment:路由参数" json:"query"`                     // 路由参数
	IsFrame    int32     `gorm:"column:is_frame;comment:是否为外链（0是 1否）" json:"isFrame"`        // 是否为外链（0是 1否）
	IsCache    int32     `gorm:"column:is_cache;comment:是否缓存（0缓存 1不缓存）" json:"isCache"`      // 是否缓存（0缓存 1不缓存）
	MenuType   string    `gorm:"column:menu_type;comment:菜单类型（M目录 C菜单 F按钮）" json:"menuType"` // 菜单类型（M目录 C菜单 F按钮）
	Visible    string    `gorm:"column:visible;comment:菜单状态（0显示 1隐藏）" json:"visible"`        // 菜单状态（0显示 1隐藏）
	Status     string    `gorm:"column:status;comment:菜单状态（0正常 1停用）" json:"status"`          // 菜单状态（0正常 1停用）
	Perms      string    `gorm:"column:perms;comment:权限标识" json:"perms"`                     // 权限标识
	Icon       string    `gorm:"column:icon;comment:菜单图标" json:"icon"`                       // 菜单图标
	CreateBy   string    `gorm:"column:create_by;comment:创建者" json:"createBy"`               // 创建者
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`          // 创建时间
	UpdateBy   string    `gorm:"column:update_by;comment:更新者" json:"updateBy"`               // 更新者
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`          // 更新时间
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`                     // 备注
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
