// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUserOnline = "sys_user_online"

// SysUserOnline mapped from table <sys_user_online>
type SysUserOnline struct {
	SessionID      string    `gorm:"column:sessionId;primaryKey;comment:用户会话id" json:"sessionId"`           // 用户会话id
	LoginName      string    `gorm:"column:login_name;comment:登录账号" json:"login_name"`                      // 登录账号
	DeptName       string    `gorm:"column:dept_name;comment:部门名称" json:"dept_name"`                        // 部门名称
	Ipaddr         string    `gorm:"column:ipaddr;comment:登录IP地址" json:"ipaddr"`                            // 登录IP地址
	LoginLocation  string    `gorm:"column:login_location;comment:登录地点" json:"login_location"`              // 登录地点
	Browser        string    `gorm:"column:browser;comment:浏览器类型" json:"browser"`                           // 浏览器类型
	Os             string    `gorm:"column:os;comment:操作系统" json:"os"`                                      // 操作系统
	Status         string    `gorm:"column:status;comment:在线状态on_line在线off_line离线" json:"status"`           // 在线状态on_line在线off_line离线
	StartTimestamp time.Time `gorm:"column:start_timestamp;comment:session创建时间" json:"start_timestamp"`     // session创建时间
	LastAccessTime time.Time `gorm:"column:last_access_time;comment:session最后访问时间" json:"last_access_time"` // session最后访问时间
	ExpireTime     int32     `gorm:"column:expire_time;comment:超时时间，单位为分钟" json:"expire_time"`              // 超时时间，单位为分钟
}

// TableName SysUserOnline's table name
func (*SysUserOnline) TableName() string {
	return TableNameSysUserOnline
}
