// Copyright (c) [2024] K. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file. or see：https://github.com/Kun-GitHub/RuoYi-Go/blob/main/LICENSE
// Author: K. See：https://github.com/Kun-GitHub/RuoYi-Go
// Email: hot_kun@hotmail.com or 867917691@qq.com

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDept = "sys_dept"

// SysDept mapped from table <sys_dept>
type SysDept struct {
	DeptID     int64     `gorm:"column:dept_id;primaryKey;comment:部门id" json:"deptId"`     // 部门id
	ParentID   int64     `gorm:"column:parent_id;comment:父部门id" json:"parentId"`           // 父部门id
	Ancestors  string    `gorm:"column:ancestors;comment:祖级列表" json:"ancestors"`           // 祖级列表
	DeptName   string    `gorm:"column:dept_name;comment:部门名称" json:"deptName"`            // 部门名称
	OrderNum   int32     `gorm:"column:order_num;comment:显示顺序" json:"orderNum"`            // 显示顺序
	Leader     string    `gorm:"column:leader;comment:负责人" json:"leader"`                  // 负责人
	Phone      string    `gorm:"column:phone;comment:联系电话" json:"phone"`                   // 联系电话
	Email      string    `gorm:"column:email;comment:邮箱" json:"email"`                     // 邮箱
	Status     string    `gorm:"column:status;comment:部门状态（0正常 1停用）" json:"status"`        // 部门状态（0正常 1停用）
	DelFlag    string    `gorm:"column:del_flag;comment:删除标志（0代表存在 2代表删除）" json:"delFlag"` // 删除标志（0代表存在 2代表删除）
	CreateBy   string    `gorm:"column:create_by;comment:创建者" json:"createBy"`             // 创建者
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`        // 创建时间
	UpdateBy   string    `gorm:"column:update_by;comment:更新者" json:"updateBy"`             // 更新者
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`        // 更新时间

	ID       int64      `gorm:"-" json:"id"`       // 部门id
	Label    string     `gorm:"-" json:"label"`    // 部门名称
	Children []*SysDept `gorm:"-" json:"children"` // 更新时间
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
