// Copyright (c) [2024] K. All rights reserved.
// Use of this source code is governed by a MIT license that can be found in the LICENSE file. or see：https://github.com/Kun-GitHub/RuoYi-Go/blob/main/LICENSE
// Author: K. See：https://github.com/Kun-GitHub/RuoYi-Go
// Email: hot_kun@hotmail.com or BusinessCallKun@gmail.com

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictType = "sys_dict_type"

// SysDictType mapped from table <sys_dict_type>
type SysDictType struct {
	DictID     int64     `gorm:"column:dict_id;primaryKey;comment:字典主键" json:"dictId"` // 字典主键
	DictName   string    `gorm:"column:dict_name;comment:字典名称" json:"dictName"`        // 字典名称
	DictType   string    `gorm:"column:dict_type;comment:字典类型" json:"dictType"`        // 字典类型
	Status     string    `gorm:"column:status;comment:状态（0正常 1停用）" json:"status"`      // 状态（0正常 1停用）
	CreateBy   string    `gorm:"column:create_by;comment:创建者" json:"createBy"`         // 创建者
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"createTime"`    // 创建时间
	UpdateBy   string    `gorm:"column:update_by;comment:更新者" json:"updateBy"`         // 更新者
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"updateTime"`    // 更新时间
	Remark     string    `gorm:"column:remark;comment:备注" json:"remark"`               // 备注
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
